export const AdminTypes = {
  GET_ORDERS_REQUEST: "@admin/GET_ORDERS_REQUEST",
  GET_ORDERS_SUCCESS: "@admin/GET_ORDERS_SUCCESS",
  GET_ORDERS_ERROR: "@admin/GET_ORDERS_ERROR",
  UPDATE_ORDER_STATUS_REQUEST:"@admin/UPDATE_ORDER_STATUS_REQUEST",
  UPDATE_ORDER_STATUS_SUCCESS:"@admin/UPDATE_ORDER_STATUS_SUCCESS",
  UPDATE_ORDER_STATUS_ERROR:"@admin/UPDATE_ORDER_STATUS_ERROR",
};
