export const ItemTypes = {
  ADD_ITEM_REQUEST: "@item/ADD_ITEM_REQUEST",
  ADD_ITEM_SUCCESS: "@item/ADD_ITEM_SUCCESS",
  ADD_ITEM_ERROR: "@item/ADD_ITEM_ERROR",
  GET_ITEM_REQUEST: "@item/GET_ITEM_REQUEST",
  GET_ITEM_SUCCESS: "@item/GET_ITEM_SUCCESS",
  GET_ITEM_ERROR: "@item/GET_ITEM_ERROR",
};
