export const OrderTypes = {
  ADD_ORDER_REQUEST: "@order/ADD_ORDER_REQUEST",
  ADD_ORDER_SUCCESS: "@order/ADD_ORDER_SUCCESS",
  ADD_ORDER_ERROR: "@order/ADD_ORDER_ERROR",
  ADD_ORDER_CAPTURE_REQUEST: "@order/ADD_ORDER_CAPTURE_REQUEST",
};
