export const tableDataTypes = {
  GET_TABLE_DATA_REQUEST: "GET_TABLE_DATA_REQUEST",
  GET_TABLE_DATA_SUCCESS: "GET_TABLE_DATA_SUCCESS",
  GET_TABLE_DATA_FAILURE: "GET_TABLE_DATA_FAILURE",

  ADD_ROW_REQUEST: "ADD_ROW_REQUEST",
  ADD_ROW_SUCCESS: "ADD_ROW_SUCCESS",
  ADD_ROW_FAILURE: "ADD_ROW_FAILURE",

  EDIT_ROW_REQUEST: "EDIT_ROW_REQUEST",
  EDIT_ROW_SUCCESS: "EDIT_ROW_SUCCESS",
  EDIT_ROW_FAILURE: "EDIT_ROW_FAILURE",

  DELETE_ROW_REQUEST: "DELETE_ROW_REQUEST",
  DELETE_ROW_SUCCESS: "DELETE_ROW_SUCCESS",
  DELETE_ROW_FAILURE: "DELETE_ROW_FAILURE",
};
